version: "3"
networks:
 docker12kube:
  driver: bridge
services:
 web:
  image: web:v1
  container_name: web
  ports:
  - "80:80"
  depends_on:
  - catalogue
 catalogue:
  image: catalogue:v1
  container_name: catalogue
  depends_on:
  - mongodb
 mongodb:
  image: mongodb:v1
  container_name: mongodb
  

 user:
  image: user:v1
  container_name: user
  depends_on:
  - mongodb
  - redis
 redis:
  image: redis
  



  
 
    