version: "3.9"
networks:
  robosanju:
    driver: bridge

services:
  web:
    image: web:v1
    container_name: web
    ports:
    - "8070:80"
    depends_on:
    - catalogue
  catalogue:
    image: catalogue:v1
    container_name: catalogue
    depends_on:
    - mongodb
  mongodb:
    image: mongodb:v1
    container_name: mongodb
  redis:
    image: redis
    container_name: redis
  user:
    image: user:v1
    container_name: user
    depends_on:
    - mongodb
    - redis

  instana-agent:
    image: instana/agent
    container_name: instana-agent
    environment:
      - INSTANA_AGENT_KEY=your_actual_agent_key_here
    networks:
      - instana-network

  instana-collector:
    image: instana/collector
    container_name: instana-collector
    environment:
      - INSTANA_AGENT_ENDPOINT=instana-agent:42699
    networks:
      - instana-network

networks:
  instana-network:
    driver: bridge
   
 
    