version: "3.9"
networks:
 docker12kube:
  driver: bridge
services:
 web:
  image: web12:v1
  container_name: web12
  ports:
  - "80:80"
  depends_on:
  - catalogue
 catalogue:
  image: catalogue12:v1
  container_name: catalogue12
  depends_on:
  - mongodb
 mongodb:
  image: mongodb12:v1
  container_name: mongodb12
  

 user:
  image: user12:v1
  container_name: user12
  depends_on:
  - mongodb
  - redis
 redis:
  image: redis
  



  
 
    