version: "3.9"
networks:
 docker12kube:
  driver: bridge
services:
 web:
  image: web12:v1
  container_name: web
  ports:
  - "80:80"
  depends_on:
  - catalogue
 catalogue:
  image: catalogue12:v1
  container_name: catalogue
  depends_on:
  - mongodb
 mongodb:
  image: mongodb12:v1
  container_name: mongodb
  volumes:
   - ./mongod.conf:/etc/mongod.conf
  ports:
   - "27017:27017"
  restart: always
  command: ["mongod", "--config", "/etc/mongod.conf"]

 user:
  image: user12:v1
  container_name: user
  depends_on:
  - mongodb
  - redis
 redis:
  image: redis12
  



  
 
    