version: "3.9"
networks:
 docker12kube:
  driver: bridge
services:
 web:
  image: web:v1
  container_name: web
  ports:
  - "80:80"
  depends_on:
  - catalogue
  - user
  - cart
  - mysql
  - shipping
 catalogue:
  image: catalogue:v1
  container_name: catalogue
  depends_on:
  - mongodb
 mongodb:
  image: mongodb:v1
  container_name: mongodb

 redis:
  image: redis
 user:
  image: user:v1
  container_name: user
  depends_on:
  - mongodb
  - redis
 cart:
  image: cart:v1
  container_name: cart
  depends_on:
  - redis
  - catalogue
 mysql:
  image: mysql:v1
  container_name: mysql
 shipping:
  image: shipping:v1
  container_name: shipping
 rabbitmq:
  image: rabbitmq
  container_name: rabbitmq
 payment:
  image: payment:v1
  container_name: payment
  depends_on:
  - rabbitmq
  

 
  



  
 
    